In [624]:
from function import *
import numpy as np
import networkx as nx
from collections import defaultdict
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [625]:
# Using Random Data

# Number of data
N = 10
# Number of features
d = 4
# Control precision bit of the output 
precision = 5
# Size of the QUBO matrix
dim = d * (2 * precision)

# Generate Random Data
X = np.random.rand(N, d)
Y = np.random.rand(N)

# If you want to perform polynomial regression
# X, d, dim = polynomialForm(X, d, dim, precision)

print(X)
print(Y)
print(d, dim)

[[0.33771271 0.11131162 0.24207253 0.93109941]
 [0.37109087 0.90399408 0.93233622 0.73108966]
 [0.04431574 0.53982683 0.58526018 0.70231093]
 [0.30387732 0.34027931 0.59892294 0.49102441]
 [0.0610724  0.35161679 0.33571539 0.28955366]
 [0.45236999 0.95963303 0.95910967 0.21640982]
 [0.83219563 0.75147191 0.14324611 0.82675327]
 [0.19509578 0.12408934 0.56268092 0.33263031]
 [0.17681057 0.96738611 0.1290571  0.06232768]
 [0.07347971 0.17482535 0.97937162 0.1512834 ]]
[0.52538489 0.99223003 0.88020413 0.80097541 0.48174045 0.44875928
 0.80674161 0.26339536 0.55023415 0.37164374]
4 40


In [626]:
XtX = np.matmul(X.T, X) # Covariance matrix
XtY = np.matmul(X.T, Y) # Relation between Features and Y

# print(XtX)
# print(XtY)

In [627]:
# Creating the graph
G = nx.Graph()
G.add_edges_from([(i, j) for i in range(dim) for j in range(i + 1, dim)])

# The matrix where we add the objective and the constraint (QUBO matrix)s
Q = defaultdict(int)

print(G)
print(Q)

Graph with 40 nodes and 780 edges
defaultdict(<class 'int'>, {})


In [628]:
generateQuboMatrix(XtX, XtY, precision, Q, d)

In [629]:
sampleset = sampling(Q)
distributions, weights, error = solve(sampleset, dim, precision, X,Y, d)

# print(distributions)
print(weights)
print("MSE Quantum : ", error)

[-0.125   0.4375  0.1875  0.6875]
MSE Quantum :  0.015263560657159222


In [630]:
clf = LinearRegression()
clf.fit(X, Y)
print(clf.coef_)
print("MSE Sklearn: ", mse(clf.predict(X),Y))

[-0.35133094  0.46952013  0.06464632  0.68612892]
MSE Sklearn:  0.014137986633270472


In [631]:
diff = 100*(error - mse(clf.predict(X),Y))/mse(clf.predict(X),Y)

print("Sklearn perform ", diff, "% better than Quantum")

Sklearn perform  7.961345933373369 % better than Quantum


In [632]:
# poly = PolynomialFeatures(degree=2)
# X_poly = poly.fit_transform(X)

# clf = LinearRegression()
# clf.fit(X_poly, Y)
# print(clf.coef_)
# print("MSE Sklearn: ", mse(clf.predict(X),Y))